name: On Pull Request -- Lint, Build, Test, Coverage

on:
  pull_request:
    branches:    
      - main
      - 'release/**'
      
jobs:
  call-workflow-passing-data:
    uses: magmaworks/actions/.github/workflows/on-merge-to-main.yml@main
